# Generated by Django 5.2.1 on 2025-06-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=14)),
                ('Email', models.CharField(max_length=100)),
                ('Telefone', models.CharField(max_length=20)),
            ],
        ),
    ]
